### ISSUE TITLE
Direct launch links don't seem to work

### ISSUE THREAD

**Issue by inducer** [gesiscss/orc2#12]
I try to construct a direct launch link as instructed by the [FAQ](https://notebooks.gesis.org/faq.html):

https://notebooks.gesis.org/binder/v2/gh/illinois-ceesd/NCSA-WEST/HEAD

However the page at which I arrive only tells me: "Failed to connect to event stream". The same repo, launched via manual input on the [front page](https://notebooks.gesis.org/binder/) launches just fine. What am I missing? Thanks in advance for the help, and thanks for hosting GESIS notebooks. (I do admit I'm not a social scientist... but I do work at a university. I hope that counts? :slightly_smiling_face: )

**Comment by rgaiacs** [comment]
Dear @inducer,

Thanks for the issue. I confirm this is a bug.

Visiting https://notebooks.gesis.org/binder/ and providing https://github.com/illinois-ceesd/NCSA-WEST/ as the GitHub repository successfully starts the build of the container.

**Comment by arnim** [comment]
@inducer thank you for reporting 👍

**Comment by rgaiacs** [comment]
Dear @inducer, this is fixed now (https://github.com/gesiscss/orc2/commit/1e9585cdd35cba83b25d31d00e8688c56528ad93).
