### ISSUE TITLE
health api response time 

### ISSUE THREAD

**Issue by arnim** [gesiscss/orc2#8]
time curl https://notebooks.gesis.org/binder/health 

```json
{"ok": true, "checks": [{"service": "Docker registry", "ok": true}, {"service": "JupyterHub API", "ok": true}, {"service": "Pod quota", "total_pods": 62, "build_pods": 8, "user_pods": 54, "quota": 120, "ok": true, "_ignore_failure": true}]}
```
```bash
curl https://notebooks.gesis.org/binder/health  0.04s user 0.02s system 0% cpu 1:03.32 total
```

Response time > 1 min 🤔

**Comment by rgaiacs** [comment]
Looks normal now.

Our server was taking too long to reply at

- May 3, 2023 4:05pm GMT+0200
- May 3, 2023 6:19pm GMT+0200
- May 3, 2023 6:57pm GMT+0200
- May 3, 2023 8:04pm GMT+0200
- May 3, 2023 10:19pm GMT+0200
- May 3, 2023 11:19pm GMT+0200
- May 3, 2023 11:53pm GMT+0200
- May 4, 2023 6:19am GMT+0200

based on our bot.

**Comment by arnim** [comment]
Are the results of the bot somewhere available / public?

**Comment by rgaiacs** [comment]
The results of the bot are at https://git.gesis.org/. I can add a bot to GitHub.

**Comment by rgaiacs** [comment]
You can use GitHub actions to test GESIS notebooks: https://github.com/gesiscss/orc2/actions/workflows/status-verification.yml

![Screenshot 2023-05-05 at 15-48-39 Actions · gesiscss_orc2](https://user-images.githubusercontent.com/1506457/236476011-7377d518-2bce-4db4-a8de-4466697b35f3.png)
